# Site settings
title: Sarah Sullivan
email: sarah@sarahsullivan.com
description: >
  Sarah Sullivan. Children's clothing designer. RISD Class of 2016.
baseurl: ""
url: "http://sarahsullivan.com"

# Build settings

markdown: kramdown

# YAML Front Matter Defaults
defaults:
  -
    scope:
      path: ""
      type: 'pages'
    values:
      layout: 'default'

stylus:
  compress: true
  path: './assets/styles'

sass_dir: './assets/styles/partials'

permalink: pretty
