# Site settings
title: Sarah Sullivan
email: sarah@sarahsullivan.com
description: >
  Sarah Sullivan. Children's clothing designer. RISD Class of 2016.
baseurl: ""
url: "http://sarahsullivan.com"

# Build settings
source: source
destination: build

layouts: source/_layouts
plugins: source/_plugins

sass:
  sass_dir: assets/style/partials

markdown: kramdown

# YAML Front Matter Defaults
defaults:
  -
    scope:
      path: ""
      type: 'pages'
    values:
      layout: 'default'
